In [1]:
!pip install kaggle
import kaggle



In [2]:
from kaggle.api.kaggle_api_extended import KaggleApi

In [3]:
api = KaggleApi()
api.authenticate()

In [4]:
api.dataset_download_cli('jangedoo/utkface-new')

Dataset URL: https://www.kaggle.com/datasets/jangedoo/utkface-new
License(s): copyright-authors


In [5]:
import zipfile

In [6]:
with zipfile.ZipFile('utkface-new.zip', 'r') as zipref:
    zipref.extractall()

In [12]:
import os
import cv2
import numpy as np

# Define the path to the cropped images
data_dir = r"C:\VS CODE\ML\utkface_aligned_cropped\crop_part1"

# Function to load and process images with ethnicity labels
def load_images_from_folder(data_dir):
    images = []
    ethnicity_labels = []
    
    for filename in os.listdir(data_dir):
        if filename.endswith(".jpg"):
            # Construct the full file path
            file_path = os.path.join(data_dir, filename)
            
            try:
                # Load the image using OpenCV
                image = cv2.imread(file_path)
                if image is None:
                    print(f"Failed to load image: {file_path}")
                    continue
                
                image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
                
                # Extract the ethnicity (race) from the filename
                # Format is typically [age]_[gender]_[race]_[date&time].jpg
                parts = filename.split("_")
                if len(parts) >= 3:
                    ethnicity = int(parts[2])  # Ethnicity is the third element
                    
                    # Append the image and ethnicity label to the lists
                    images.append(image)
                    ethnicity_labels.append(ethnicity)
                else:
                    print(f"Filename format incorrect for {filename}")
            
            except Exception as e:
                print(f"Error processing {file_path}: {str(e)}")
    
    # Convert lists to numpy arrays for ML models
    images = np.array(images)
    ethnicity_labels = np.array(ethnicity_labels)
    
    return images, ethnicity_labels

# Load images and ethnicity labels
images, ethnicity_labels = load_images_from_folder(data_dir)
print(f"Loaded {len(images)} images with corresponding ethnicity labels.")

# Optionally, create a mapping for better understanding
ethnicity_mapping = {
    0: "White",
    1: "Black",
    2: "Asian",
    3: "Indian",
    4: "Others"
}

# Print distribution of ethnicities
for ethnicity_id, ethnicity_name in ethnicity_mapping.items():
    count = np.sum(ethnicity_labels == ethnicity_id)
    print(f"{ethnicity_name}: {count} images")

Error processing C:\VS CODE\ML\utkface_aligned_cropped\crop_part1\61_1_20170109142408075.jpg.chip.jpg: invalid literal for int() with base 10: '20170109142408075.jpg.chip.jpg'
Error processing C:\VS CODE\ML\utkface_aligned_cropped\crop_part1\61_3_20170109150557335.jpg.chip.jpg: invalid literal for int() with base 10: '20170109150557335.jpg.chip.jpg'
Loaded 9778 images with corresponding ethnicity labels.
White: 5265 images
Black: 405 images
Asian: 1553 images
Indian: 1452 images
Others: 1103 images


In [11]:
print(labels)
print(images)

[100 100 101 ...   9   9   9]
[[[[219 223 226]
   [232 235 240]
   [232 237 243]
   ...
   [226 233 241]
   [219 226 234]
   [220 227 235]]

  [[228 232 235]
   [236 239 244]
   [230 234 243]
   ...
   [224 231 239]
   [220 227 235]
   [220 227 235]]

  [[233 236 241]
   [236 239 244]
   [226 230 239]
   ...
   [220 227 235]
   [221 228 236]
   [219 226 234]]

  ...

  [[ 25  47  88]
   [ 35  59 103]
   [ 35  67 116]
   ...
   [171 175 178]
   [182 183 187]
   [184 188 191]]

  [[ 27  50  92]
   [ 22  49  92]
   [ 18  49  96]
   ...
   [254 255 255]
   [255 255 255]
   [254 255 255]]

  [[ 22  47  88]
   [  9  36  79]
   [  3  34  80]
   ...
   [253 253 251]
   [255 255 253]
   [255 255 253]]]


 [[[ 51  41  32]
   [ 50  40  31]
   [ 48  38  29]
   ...
   [ 85  79  67]
   [ 81  74  64]
   [ 79  72  62]]

  [[ 51  41  32]
   [ 50  40  31]
   [ 48  38  29]
   ...
   [ 86  80  68]
   [ 82  75  65]
   [ 80  73  63]]

  [[ 50  40  31]
   [ 48  38  29]
   [ 47  37  28]
   ...
   [ 87  81  69